# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [1]:
import pandas as pd

df = pd.read_csv('vgsalesGlobale.csv')

In [2]:
total_global_sales = df['Global_Sales'].sum()
print(f"Total Global Sales: {total_global_sales}")

Total Global Sales: 8920.44


In [3]:
highest_global_sales_game = df.loc[df['Global_Sales'].idxmax()]
print(f"Game with Highest Global Sales: {highest_global_sales_game['Name']}")

Game with Highest Global Sales: Wii Sports


In [4]:
average_sales_na = df['NA_Sales'].mean()
average_sales_eu = df['EU_Sales'].mean()
average_sales_jp = df['JP_Sales'].mean()
average_sales_other = df['Other_Sales'].mean()
print(f"Average NA Sales: {average_sales_na}")
print(f"Average EU Sales: {average_sales_eu}")
print(f"Average JP Sales: {average_sales_jp}")
print(f"Average Other Sales: {average_sales_other}")

Average NA Sales: 0.26466742981082064
Average EU Sales: 0.14665200626581515
Average JP Sales: 0.077781660441017
Average Other Sales: 0.0480630196409206


In [5]:
top_5_genres = df.groupby('Genre')['Global_Sales'].sum().sort_values(ascending=False).head(5)
print("Top 5 Most Popular Game Genres Based on Global Sales:")
print(top_5_genres)

Top 5 Most Popular Game Genres Based on Global Sales:
Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64


In [6]:
total_sales_by_genre_region = df.groupby('Genre')[['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales']].sum()
most_popular_genre_na = total_sales_by_genre_region['NA_Sales'].idxmax()
print(f"Most Popular Genre in North America: {most_popular_genre_na}")

Most Popular Genre in North America: Action


In [7]:
last_10_rows = df.tail(10)
print("Last 10 Rows of the Dataset:")
print(last_10_rows)

Last 10 Rows of the Dataset:
        Rank                                               Name Platform  \
16588  16591                                   Mega Brain Boost       DS   
16589  16592  Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...      PSV   
16590  16593  Eiyuu Densetsu: Sora no Kiseki Material Collec...      PSP   
16591  16594                                Myst IV: Revelation       PC   
16592  16595                                           Plushees       DS   
16593  16596                 Woody Woodpecker in Crazy Castle 5      GBA   
16594  16597                      Men in Black II: Alien Escape       GC   
16595  16598   SCORE International Baja 1000: The Official Game      PS2   
16596  16599                                         Know How 2       DS   
16597  16600                                   Spirits & Spells      GBA   

         Year         Genre              Publisher  NA_Sales  EU_Sales  \
16588  2008.0        Puzzle  Majesco Entertainment      0.01

In [8]:
top_3_platforms = df.groupby('Platform')['Global_Sales'].sum().sort_values(ascending=False).head(3)
print("Top 3 Gaming Platforms with Highest Global Sales:")
print(top_3_platforms)

Top 3 Gaming Platforms with Highest Global Sales:
Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64


In [9]:
total_global_sales_by_genre = df.groupby('Genre')['Global_Sales'].sum()
market_share_by_genre = (total_global_sales_by_genre / total_global_sales) * 100
print("Market Share for Each Genre:")
print(market_share_by_genre)

Market Share for Each Genre:
Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64


In [10]:
correlation_na_eu = df['NA_Sales'].corr(df['EU_Sales'])
print(f"Correlation Coefficient between NA_Sales and EU_Sales: {correlation_na_eu}")

Correlation Coefficient between NA_Sales and EU_Sales: 0.7677267483702624


## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.


In [12]:
english_spanish_dict = {
    'hello': 'hola',
    'goodbye': 'adiós',
    'please': 'por favor',
    'thank you': 'gracias',
    'yes': 'sí',
    'no': 'no',
    'cat': 'gato',
    'dog': 'perro',
    'house': 'casa',
    'car': 'coche'
}
def lookup_word():
    while True:
        english_word = input("Enter an English word (or type 'exit' to quit): ").strip().lower()
        
        if english_word == 'exit':
            print("Exiting the dictionary")
            break
        
        if english_word in english_spanish_dict:
            print(f"The Spanish translation of '{english_word}' is '{english_spanish_dict[english_word]}'.")
        else:
            print(f"the translation for '{english_word}' is not available.")

lookup_word()

The Spanish translation of 'hello' is 'hola'.
Exiting the dictionary. Goodbye!



## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [4]:
important_emails = []
promotions_emails = []
spam_emails = []

def classify_emails(emails):
    important_keywords = ["meeting", "project", "urgent", "important", "deadline"]
    promotions_keywords = ["sale", "discount", "offer", "deal", "promotion"]
    spam_keywords = ["win", "prize", "free", "click", "subscribe"]

    for email in emails:
        email_lower = email.lower()
        if any(keyword in email_lower for keyword in important_keywords):
            important_emails.append(email)
            
        elif any(keyword in email_lower for keyword in promotions_keywords):
            promotions_emails.append(email)
            
        elif any(keyword in email_lower for keyword in spam_keywords):
            spam_emails.append(email)
            
        else:
            spam_emails.append(email)

    return important_emails, promotions_emails, spam_emails

emails = [
    "Meeting tomorrow at 10am",
    "Huge discount on your favorite products",
    "You have won a prize! Click here to claim",
    "Project deadline is next week",
    "Exclusive offer just for you",
    "Free subscription for a limited time"
]

important, promotions, spam = classify_emails(emails)

In [5]:
print("Important Emails:", important)
print("Promotions Emails:", promotions)
print("Spam Emails:", spam)

Important Emails: ['Meeting tomorrow at 10am', 'Project deadline is next week']
Promotions Emails: ['Huge discount on your favorite products', 'Exclusive offer just for you']
Spam Emails: ['You have won a prize! Click here to claim', 'Free subscription for a limited time']


## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [2]:
shopping_cart = []

print("Welcome to the AI Response Simulator and Investment Decision Store!")
print("Available products:")
print("1. AI Response Simulator")
print("2. Investment Decision")
print("3. Exit")

while True:
    choice = input("Enter the number of the product you want to add to the cart (or 'q' to quit): ").strip().lower()
    
    if choice == 'q':
        break
    
    try:
        choice = int(choice)
        if choice < 1 or choice > 3:
            print("Invalid choice. Please enter a number between 1 and 3.")
            continue
        
    except ValueError:
        print("Invalid input. Please enter a number between 1 and 3.")
        continue
    
    if choice == 1:
        shopping_cart.append("AI Response Simulator")
        print("AI Response Simulator has been added to your cart.")
        
    elif choice == 2:
        shopping_cart.append("Investment Decision")
        print("Investment Decision has been added to your cart.")
        
    elif choice == 3:
        break

print("Your shopping cart contains:")
for item in shopping_cart:
    print(f"-{item}")

print("Thank you for shopping, Goodbye")

Welcome to the AI Response Simulator and Investment Decision Store!
Available products:
1. AI Response Simulator
2. Investment Decision
3. Exit
AI Response Simulator has been added to your cart.
Investment Decision has been added to your cart.
Your shopping cart contains:
- AI Response Simulator
- Investment Decision
Thank you for shopping with us! Goodbye!


## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [1]:
import numpy as np

arr_sum = []
arr_product = []

arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

for i in range(len(arr1)):
    arr_sum.append(arr1[i] + arr2[i])
    arr_product.append(arr1[i] * arr2[i])

arr_sum = np.array(arr_sum)
arr_product = np.array(arr_product)

print("Element-wise addition:", arr_sum)
print("Element-wise product:", arr_product)

Element-wise addition: [ 7  9 11 13 15]
Element-wise product: [ 6 14 24 36 50]


## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [1]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
reshaping = arr.reshape(3,4)
print(reshaping)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [2]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])

horizontal_concat = np.concatenate((arr1, arr2), axis=1)
print("Horizontally concatenated array:", horizontal_concat)

vertical_concat = np.concatenate((arr1, arr2), axis=0)
print("Vertically concatenated array:", vertical_concat)

Horizontally concatenated array: [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
Vertically concatenated array: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## Task 7
* Reverse A List In Python Using Slicing


In [13]:
original_list = [1, 2, 3, 4, 5]
reversed_list = original_list[::-1]
print(reversed_list)

[5, 4, 3, 2, 1]


# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.